// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XRayFractureDetection.DataAccess.Context;

#nullable disable

namespace XRayFractureDetection.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XRayFractureDetection.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageHash");

                    b.ToTable("AnalysisRequests");
                });

            modelBuilder.Entity("XRayFractureDetection.Domain.Entities.DetectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<float>("BoundingBoxHeight")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxWidth")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("real");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("real");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<bool>("IsFracture")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId");

                    b.ToTable("DetectionResults");
                });

            modelBuilder.Entity("XRayFractureDetection.Domain.Entities.DetectionResult", b =>
                {
                    b.HasOne("XRayFractureDetection.Domain.Entities.AnalysisRequest", "AnalysisRequest")
                        .WithMany("DetectionResults")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRequest");
                });

            modelBuilder.Entity("XRayFractureDetection.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Navigation("DetectionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
